# Generated by Django 4.1.1 on 2022-10-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_product_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=50)),
                ("lname", models.CharField(max_length=50)),
                ("phno", models.CharField(max_length=12)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=500)),
            ],
        ),
    ]
