# Generated by Django 4.1.1 on 2022-10-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_order_address_order_phno"),
    ]

    operations = [
        migrations.AddField(
            model_name="order", name="status", field=models.BooleanField(default=False),
        ),
    ]
